watch:
  directories:
    - src
    - tests
  fileMask: '*.php'
notifications:
  passingTests: false
  failingTests: false
hideManual: false
phpunit:
  binaryPath: vendor/bin/phpunit
  configuration: phpunit.xml
  arguments:  --no-coverage --testdox
  timeout: 180